### ISSUE TITLE
Doesn't work if Tenant Name is used

### ISSUE THREAD

**Issue by simhams** [Azure-Samples/active-directory-dotnet-webapp-webapi-oauth2-appidentity#12]
For AppSetting "ida:Tenant", the sample suggests "[Enter tenant name, e.g. contoso.onmicrosoft.com]". Using a tenant name doesn't work, but using a tenant id works fine.

**Comment by Theraghav** [comment]
For me it works with just the Tenant name

**Comment by jmprieur** [comment]
This also works for me with the tenant name. Closing this issue (must have been fixed)
