### ISSUE TITLE
Using URI in TodoListResourceId doesn't work. App ID works

### ISSUE THREAD

**Issue by Sandiejat** [Azure-Samples/active-directory-dotnet-webapp-webapi-oauth2-appidentity#13]
Using the App ID URI doesn't work. Adding an App ID works fine.

<add key="todo:TodoListResourceId" value="[Enter App ID URI of TodoListService, e.g. https://contoso.onmicrosoft.com/TodoListService]" />

**Comment by Theraghav** [comment]
Same goes for 'ida:Audience' and 'todo:TodoListResourceId'
in Service web.config
    <add key="ida:Audience" value="<App-ID of Todo Service>" />
in Web App web.config
 <add key="todo:TodoListResourceId" value="<App-ID of Todo Service>" />

**Comment by Theraghav** [comment]
Same goes for 'ida:Audience' and 'todo:TodoListResourceId'
in Service web.config
`    <add key="ida:Audience" value="<App-ID of Todo Service>" />`
in Web App web.config
` <add key="todo:TodoListResourceId" value="<App-ID of Todo Service>" />`

**Comment by dean-azure** [comment]
I found the same thing.   When  used the appid for both Audience and TodoListResourceId, the application ran in local host.   However, it still doesn't work when I attempt to deploy to azure no matter what I use.

This scenario seems like it would be fairly common.   Is there an actual working example for a webapp to use a webservice?   This shouldn't be this heard?    Is Azure still not ready for prime time?   Should I be using AWS instead?    This is really frustrating!

**Comment by jmprieur** [comment]
Sorry @dean-azure for your frustration. I have not looked at the sample yet. It's in the list of samples to review and cleanup which I want to address ASAP.

From it name it's using the [Client credentials flow](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Client-credential-flows). That is the Web App accesses the Web API in its own name (not in the name of a user). Is it what you want? Or would you want a Web App calling a Web API in the name of the user (in that case see [Web applications](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-code-samples#web-applications)

More generally here is a comprehensive list of our samples: [Azure Active Directory code samples (V1 endpoint)](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-code-samples)

**Comment by dean-azure** [comment]
I finally figured out the problem.    But before I explain, the documentation for this project are inaccurate.   After many hours of frustrating trial and error I started to make headway from @Theraghav comments about setting the AppId.   The documentation should be updated to include his updates.
But even after updating the documentation, it worked locally but did not work when I deployed it to an azure environment.

The other change I had to make was I had to change:
        public void ConfigureAuth(IAppBuilder app)
        {
            app.UseWindowsAzureActiveDirectoryBearerAuthentication(
                new WindowsAzureActiveDirectoryBearerAuthenticationOptions
                {
                    Audience = ConfigurationManager.AppSettings["ida:Audience"],
                    Tenant = ConfigurationManager.AppSettings["ida:Tenant"]
                });
        }

To:

public void ConfigureAuth(IAppBuilder app)
{

	app.UseWindowsAzureActiveDirectoryBearerAuthentication(
			new WindowsAzureActiveDirectoryBearerAuthenticationOptions
			{

				Tenant = ConfigurationManager.AppSettings["ida:Tenant"],
				TokenValidationParameters = new TokenValidationParameters
				{
					ValidAudience = ConfigurationManager.AppSettings["ida:Audience"],
                    ValidateAudience=false
					}
				});
								
}

**Comment by jmprieur** [comment]
@dean-azure : FYI, @kalyankrishna1 has started improving the sample.

**Comment by jmprieur** [comment]
The sample was cleaned-up, and even have App creation scripts : See https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-oauth2-appidentity#step-2--register-the-sample-with-your-azure-active-directory-tenant
