### ISSUE TITLE
Exception: The user or administrator has not consented to use the application

### ISSUE THREAD

**Issue by timomta** [Azure-Samples/active-directory-dotnet-webapp-webapi-oauth2-appidentity#14]
Hello, I checked and double checked my setup of this sample, but the following call in the ToDoListController (line 58 TodoListController.cs in the WebApp):
                result = await authContext.AcquireTokenSilentAsync(todoListResourceId, credential, new UserIdentifier(userObjectID, UserIdentifierType.UniqueId));

Throws the following exception when I click the ToDo List menu item to access the API:
-		InnerException	{"AADSTS65001: The user or administrator has not consented to use the application with ID '243dba68-8222-4b56-b16a-a1a98bc0bcfb'. Send an interactive authorization request for this user and resource.\r\nTrace ID: 72303ad3-3a2a-4b31-a79e-7869828018ea\r\nCorrelation ID: 40eb9bfc-b293-434f-9b49-4604f5ac5af6\r\nTimestamp: 2017-01-17 03:57:48Z"}	System.Exception {Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException}

To me it seems like the initial login of the native user should display the GUI on the IDP asking for user consent to allow access to profile information. Is this the problem? I'm not sure what the issue really is or what I've done wrong.

**Comment by VitorX** [comment]
There is no `AcquireTokenSilentAsync` method used in this project, please ensure that you are using the orignal project. Or you may need provide the relative code you were changing and the scenario you are handling.

**Comment by timomta** [comment]
Yes, you're correct. I opened an issue in the wrong repository. My apologies. Too many browser tabs open.
