### ISSUE TITLE
Do we need the step to configure permissions to the WebAPI in this scenario?

### ISSUE THREAD

**Issue by imtiazh** [Azure-Samples/active-directory-dotnet-webapp-webapi-oauth2-appidentity#15]
This sample uses the application's identity (instead of the user's identity) to talk to downstream WebAPI.

Do we need the step below? I thought this is only needed in the case of user’s identity as in “WebApp-WebAPI-OpenIDConnect-DotNet”
Configure Permissions for your application - in the Settings menu, choose the 'Required permissions' section, click on Add, then Select an API, and type 'TodoListService' in the textbox. Then, click on Select Permissions and select 'Access TodoListService'.

**Comment by jmprieur** [comment]
We do need this step, so that Azure AD accepts to provide to the Web App a token for the Web API.
