### ISSUE TITLE
Why one needs to configuration permissions?

### ISSUE THREAD

**Issue by rahulvmarathe** [Azure-Samples/active-directory-dotnet-webapp-webapi-oauth2-appidentity#17]
Step # 9 reads " Configure Permissions for your application - in the Settings menu, choose the 'Required permissions' section, click on Add, then Select an API, and type 'TodoListService' in the textbox. Then, click on Select Permissions and select 'Access TodoListService'.".

However without setting the permissions i am able to call the API from the Web App; what is the significance of setting the permission?

**Comment by jmprieur** [comment]
The reason why this was working is that the audience was not validated in the Web App (See Startup.auth.cs). This is now the case.
