### ISSUE TITLE
Instanciate an Authentication context for each request as Authentication is not thread safe

### ISSUE THREAD

**Issue by jmprieur** [Azure-Samples/active-directory-dotnet-webapp-webapi-oauth2-appidentity#23]
See https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1501#issuecomment-463944245

cc: @kalyankrishna1 @henrik-me

**Comment by TiagoBrenck** [comment]
Closing as we are archiving this sample. 

The newer one can be found at: https://github.com/Azure-Samples/active-directory-dotnetcore-daemon-v2
