### ISSUE TITLE
External API's Calling My API Secured with Azure Active Directory

### ISSUE THREAD

**Issue by RehanSaeed** [Azure-Samples/active-directory-dotnet-webapp-webapi-oauth2-appidentity#8]
If I have a Web API secured with Azure Active Directory, is this the flow used for calling it from another Web API?

If the calling Web API is an external application, is the answer the same?

**Comment by jmprieur** [comment]
@RehanSaeed 
Let's name upstream the calling Web API; and downstream the called Web API.
it depends on whether you want to call downstream from upstream in the name of the user or in the name of the application itself.
- if you want to call downstream in the name of the user, you'd need to use the On-behalf-of flow: See [Service to service calls on behalf of the user](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Service-to-service-calls-on-behalf-of-the-user)
- if you want to call downstream in the name of the upstream Web API (with no user), then client credentials, as illustrated by this sample, is the thing to do. See [Client credential flows](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Client-credential-flows)

**Comment by jmprieur** [comment]
Closing this issue as it's now answered.
