### ISSUE TITLE
Possible security issue

### ISSUE THREAD

**Issue by thinkthencode** [Azure-Samples/active-directory-dotnet-webapp-webapi-oauth2-appidentity#9]
Any client can get the token for our ToDoList API using it's creds and resource Id of ToDoList API. We pass that token from client to ToDoList and on service side we only use tenant Id and Audience to validate token.

Why is there nothing showing usage of SCOPE claim?

**Comment by jmprieur** [comment]
Azure AD will make sure that the token is for the right audience and sign it. It's enough to validate the token (See [Validating tokens](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/ValidatingTokens))

**Comment by jmprieur** [comment]
Closing this issue as it's now answered
